// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBICEc3XgXNRYatrom2MGe4PQWTRGv6c',
    appId: '1:53771508446:web:f245286a3e33960bcd004f',
    messagingSenderId: '53771508446',
    projectId: 'health-app-51e9e',
    authDomain: 'health-app-51e9e.firebaseapp.com',
    storageBucket: 'health-app-51e9e.firebasestorage.app',
    measurementId: 'G-BRZ6ZFEGWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGxvzgDVzeLOZpa4KkjcWVUoKgPgQROW4',
    appId: '1:53771508446:android:c59f776b5924579fcd004f',
    messagingSenderId: '53771508446',
    projectId: 'health-app-51e9e',
    storageBucket: 'health-app-51e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqCngGzRjL6tX4KoKlD3k8z9nh4kLz2Fw',
    appId: '1:53771508446:ios:7372c34755926997cd004f',
    messagingSenderId: '53771508446',
    projectId: 'health-app-51e9e',
    storageBucket: 'health-app-51e9e.firebasestorage.app',
    iosBundleId: 'com.example.healthApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqCngGzRjL6tX4KoKlD3k8z9nh4kLz2Fw',
    appId: '1:53771508446:ios:7372c34755926997cd004f',
    messagingSenderId: '53771508446',
    projectId: 'health-app-51e9e',
    storageBucket: 'health-app-51e9e.firebasestorage.app',
    iosBundleId: 'com.example.healthApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADBICEc3XgXNRYatrom2MGe4PQWTRGv6c',
    appId: '1:53771508446:web:37dce0f2f90313c5cd004f',
    messagingSenderId: '53771508446',
    projectId: 'health-app-51e9e',
    authDomain: 'health-app-51e9e.firebaseapp.com',
    storageBucket: 'health-app-51e9e.firebasestorage.app',
    measurementId: 'G-4PRXDTDRC9',
  );
}
